### ISSUE TITLE
Method undefined

### ISSUE THREAD

**Issue by tope68** [tope68/ltoregister#2]
Miert undefined az ltoforms-ban az addregister method hivas? A startup/server/index.js-ben benne van method.js importja.

**Comment by tothand** [comment]
Nem teszteltem, de ranezesre szerintem csak annyi a gond, hogy a server/main.js-ben nincs importalva a startup/server/index.js

**Comment by tope68** [comment]
Hmm, jogos.....most mar mas is a hiba :-O Most azt írja, hogy method 13:4 ben unexpected token, de nem talalom mi a gond. Nyilvan valami szintaktika gondolom...

**Comment by tothand** [comment]
git commit -> push hogy lassam en is :)

**Comment by tope68** [comment]
A method.js nem valtozott ez nem megy, ami most ott van

**Comment by tothand** [comment]
Kozben megneztem, a hiba egyszeru:

```
Meteor.methods({ <<<<< ITT nyitsz egy JSON objectet**
	addRegister: function({ltoa, ltob}) { <<< ITT adnod kell egy name:value parost, ahol a name a method neve lesz, a value meg a fuggveny amit hiv. Erre csak azert nem adott hibat, mert alapvetoen valid ha csak siman egy function-t irsz oda, marmint szintaktikailag, de logikailag nem valid**
		// adat validálás valamivel


	  /*  if (! Meteor.userId()) {
      		throw new Meteor.Error('not-authorized'); */
    }, <<< IDE kell egy vesszo, mert a JSON-ben felsorolod a objectben talalhato name:value parokat**

    'LTOs.insert' : function(){ <<< ITT szinten egy name:value par kell**
        return {
    	actualDate: new Date(),
    	ltoAnumber: ltoa,
    	ltoBnumber: ltob,
    	// user: Meteor.userId()
        }
    }
 
});
```

Tehat az altalanos formatum:
```
Meteor.methods({
    'method.name': function(parameterek){
        //valami kod
        return valami_ertek_ha kell;
    },
    'masik.method':function(params){
        //...
    }
    ...
})
```

**Comment by tope68** [comment]
Es ES6  => formaban hogy lenne? En egy ilyen pl alapjan csinaltam

**Comment by tothand** [comment]
A masodik peldaba direkt irtam 2 parametert amit eleve "kibont" az ES6 nev szerint, hogy legyen egy olyan pelda is
```
Meteor.methods({
    'method.name': (parameterek) => {
        //valami kod
        return valami_ertek_ha kell;
    },
    'masik.method':({param1,param2}) => {
        //...
    }
    ...
})
```

**Comment by tope68** [comment]
Feladom...nem tudom ertelmezni.....

**Comment by tope68** [comment]
Ezt a 2 pl-t neztem
https://themeteorchef.com/tutorials/methods
https://github.com/designorant/leveluptuts__meteor-react-for-everyone/blob/master/server/methods.js

**Comment by tothand** [comment]
Amiket neztel peldak azok csak akkor mukodnek, ha nincs a method neveben PONT, ebben az esetben lehet egyszerusiteni a szintaktikan es siman

```
Meteor.methods({
    valamiFuggveny(parameter) => {
        return valami;
    },
    valamiMas() => {
        return xxx;
    }
})
```

**Comment by tope68** [comment]
Ez mukodik
Meteor.methods({
	addRegister: ({ltoa, ltob}) => {
		// adat validálás valamivel
	  /*  if (! Meteor.userId()) {
      		throw new Meteor.Error('not-authorized'); */
     	return LTOs.insert({
    		actualDate: new Date(),
	    	ltoAnumber: ltoa,
	    	ltoBnumber: ltob,
	    	status: 'Aktív',
	    	// user: Meteor.userId()
    	});
    },
 });

**Comment by tope68** [comment]
Megvan az elso rekordom! :-)

**Comment by tope68** [comment]
Na agyon vagta a fit, amit nagy nehezen megcsinaltam...

**Comment by tothand** [comment]
Na, itt vagyok, csak vacsiztam.

Azert nem ertetted miert irom amit irok, mert total baromsagot irtam.
En azt lattam elso ranezesre, hogy KETTO DB method-od van, csak rosszul vannak leirva...sorry, nem akartalak bevinni az erdobe, de jol kivagtad magad :)

Mit vagott haza a git? Mit csinaltal es mi lett a vegeredmenye?

**Comment by tope68** [comment]
Hat most tenyleg ott tartottam, hogy hagyom ezt az egeszet a francba.......A git lehozta amit irtal es felulcsapta, azt, amit eppen kikuzdottem. Most visszacsinaltam ha jol latom akkor ez most jo

**Comment by tothand** [comment]
A git nem "csap felul" semmit. Legrosszabb esetben conflict-kent kezeli az egymassal ellent mondo modositasokat, amiket meg kell tanulni kezelni (ertsd: nem racsapni a YES gombra, ha kerdes valamit :D )
Orulok, hogy megoldodott.

Latod milyen jo lecke volt, hogy hulyeseget irtam es rajottel, javitottad, annak ellenere amit irtam!
(bocs, tenyleg nem akartalak megzavarni, legkozelebb jobban atgondolom a kod mukodeset)

**Comment by tope68** [comment]
Semmi gond! :-) Hat az nem felulcsapas, hogy te javitasod kerult le ide a C-mre :-) ?

**Comment by tothand** [comment]
Ami egyszer bekerult a git-be az ott is marad. Tehat nem felulcsapta, hanem az "uj verziot lattad".
```git reset --hard master@{1}```
Ez visszaallitja az utolso commit-ra az allapotot. Szoval nem felulirja, hanem egy uj verziot tolt le, de a regi benne marad a verziokovetesben.

Ha pedig nem volt meg elmentve az utolso modositasod lokalban, akkor nem irja felul, hanem conflict-ra allitja amig nem resolve-olod.

**Comment by tope68** [comment]
ok, ez meg magas kicsit de majd igyekszem :-)

**Comment by tothand** [comment]
Nekem is eltartott egy darabig mire raereztem :)

https://git-scm.com/doc

Illetve stackoverflow.com tele van tok jo valaszokkal a megfelelo kerdesekre
