### ISSUE TITLE
nem latszik collection adat console logban (sem)

### ISSUE THREAD

**Issue by tope68** [tope68/ltoregister#3]
Na megint teljesen elakadtam :-( Semmilyen mongo adat nem kinyerhető consol logban mert a collectionnevre azt mondja not defined. GUIs mongo toolban latszik a ket rekord ami benne van.Olyan mintha nem futna a meteor mongoja

**Comment by tothand** [comment]
Az ltolist.js-be kell egy

```import LTOs from '../../api/ltos/collection.js';```

Valamint a ```{console.log(ltos.find().fetch())}``` helyett ```{console.log(LTOs.find().fetch())}``` kell, mert a kis- es nagybetuk szamitanak. 

Mar, ha jol ertettem a hibat.

**Comment by tope68** [comment]
Igen jol ertetted csak azt nem ertem, hogy a bongeszoben miert nem megy az LTOs.find().fetch()?

**Comment by tothand** [comment]
Az import ott van?
Nekem mukodik ugy ahogy fent irtam

**Comment by tope68** [comment]
Igen ott van

**Comment by tothand** [comment]
commitold fel a mostani valtozatodat

**Comment by tope68** [comment]
Most megy...mindjart ott lesz

**Comment by tothand** [comment]
Akkor most vagy nem ertem a kerdest vagy valami mas hiba van.
Nalam teljesen jol mukodik amit most huztam le.

Itt egy screenshot:
https://www.dropbox.com/s/i14mvo3imaqzi0h/Screenshot%202017-04-23%2016.35.34.png?dl=0

Nyilvan nalam nincs az a DB-ben ami nalad, ezert a rogzites menupontban nyomtam egy mentest es utana neztem meg.

**Comment by tope68** [comment]
Ahhh fejbevagom magam....ra kellett frisiteni, majd klikk a menupontra es most mar van object-em. Koszi :-)

**Comment by tothand** [comment]
Hehe...a lenyeg, hogy mukodik.
