### ISSUE TITLE
Tablazatban nics adat

### ISSUE THREAD

**Issue by tope68** [tope68/ltoregister#4]
Ujabb elakadas. react-bootstarp-table package ment fel. Itt [(http://allenfang.github.io/react-bootstrap-table/example.html#basic)] a leiras hozza. Egy tomb az adatparametere, de hiaba probalkozom nem tudok jo tombot csinalni az adatokbol pedig a tomb megvan a console logban latszik

**Comment by tothand** [comment]
A dataArray ugy nez ki, hogy egy tomb, aminek 1db eleme van, ami egy tomb, amiben vannak az objectek.
Ezt a legegyszerubben ugy tudod megoldani, hogy ezt a kodot:
```
        	const dataArray=[this.ltodatas().map((ltodata)=>{
                console.log(ltodata);
        		return ltodata
        	})];
```

Atirod erre
```
        	const dataArray=this.ltodatas().map((ltodata)=>{
                console.log(ltodata);
        		return ltodata
        	});
```
A [....] felesleges.
Ha megnezed, te egy tombot keszitettel a this...map...visszateresi tombjebol, ezert lett beagyazott tomb.

**Comment by tope68** [comment]
Kiraly vagy! :-)

**Comment by tope68** [comment]
Mar csak az a gond, hogy egyaltaln nem mukodik a bootsrap sehol a tabla is szet van esve meg a menuben sem mukodik az activeclassname es a menu hover sem.

**Comment by tothand** [comment]
Az example oldalon ez van:
`<BootstrapTable data={products} striped hover>`

A striped hover hianyzik

**Comment by tothand** [comment]
Marmint ez a tablazatra vonatkozik nyilvan.
A menut mindjart nezem.

**Comment by tope68** [comment]
Nem nem ez a gond. Maga a tabla van szetesve, a header sor nem olyan szeles mint az alatta levo adatsor, a header es az adatsor kozott kihagyas van

**Comment by tothand** [comment]
A main.html-be a `<title>` sor utan masold be ezt:

`<link rel="stylesheet" href="https://npmcdn.com/react-bootstrap-table/dist/react-bootstrap-table-all.min.css">`

**Comment by tope68** [comment]
Megint kirajy vagy en meg tok hulye ezt en is kiguglizhattam volna :-( Akkor az activeclassname is valami ilyen gond lehet

**Comment by tope68** [comment]
Ehhez eszembe jutott, hogy akkor romlott el, amikor az <a> tag helyett Link to lett

**Comment by tothand** [comment]
Na, megvan. Nem egyszeru :)

A `<Link...>` komponens valojaban csak egy `<a....>` tag-et hoz letre a megfelelo parameterekkel. A bootstrap NavBar viszont az <li> elemen varja az active class-t, cserebe az alatta levo <a>-nak a :focus pseudo-class-ra transparent backgound-ot ad.

A megoldas egy custom Link wrapper komponens, ez mindjart commitolom.
