### ISSUE TITLE
nem lehet kikommentelni sorokat a return div szeciojaban

### ISSUE THREAD

**Issue by tope68** [tope68/ltoregister#5]
Sem a // sem a /* */ paros nem mukodik, nem "lesz megjegyzes" hiaba teszem be oket es ki sem szurkulnek

**Comment by tothand** [comment]
http://wesbos.com/react-jsx-comments/

**Comment by tope68** [comment]
Bakker mar mindent felturtam...tok hulye vagyok... :-( koszi

**Comment by tothand** [comment]
Nincs mit
