### ISSUE TITLE
componens meghívasa parameterrel

### ISSUE THREAD

**Issue by tope68** [tope68/ltoregister#6]
Ez lehet nem annyira levelezos lesz :-) Nyilvan ez alapkerdes, de nem tudtam osszetenni a peldakbol. A feladat hogy az ltolist tablajaban a csere gombra kattintva hivjuk meg az ltoform componenst atadva neki az ltoA és ltoB aktualis erteket. Azt ott modositjuk az ertekeket (kicserletuk a kazettat kovetkezore) ezzel uj rekordot hozunk letre es visszaterunk az ltolist-hez. Amiket neztem hozza parameteres router, props kezeles, de nem all ossze...

**Comment by tothand** [comment]
Igen, ez kicsit hosszadalmasabb, de alapvetoen ket megoldas van:

list -> form (props-ban az infok + propsban a modosito fuggveny is)
list -> form (props-ban csak az ID) -> form komponensen belul meteor lekerdezes+method hivas

Eggyel kifinomultabb, ha redux-ot hasznalsz, de az meg nekem is magas volt, hiaba "hasznalom" a webhd-ben, nem ugy ahogy kellene.

**Comment by tope68** [comment]
Az ID atadasra szavaznek es ahho igazitanam az ltoslist komponens mukodest

**Comment by tope68** [comment]
Na teljesen megakadtam, tobb kerdes is van, de majd ha lesz kis idod, ez itt levelben nem fog menni......Azt hiszem kimegyek kicsit gurulni :-)
