### ISSUE TITLE
if feletele hogy csinalhat ertekadast?

### ISSUE THREAD

**Issue by tope68** [tope68/ltoregister#7]
Na egy ujabb erthetetlenseg. Van egy ilyen if row.status='lezart' akkor legyen valami ha nem akkor valami mas. Erre a valami erteke megvaltozik az if feltetelben megadottra. Teljes kaosz. Hogy lehet ez ha meg a kornyeken sincs ertekadas a felteleben vizsgalat hgy adhat erteket? Total nem ertem

**Comment by tope68** [comment]
Raadasul maga feltelel kiertekelese false ra se mehetne arra az agra

**Comment by tothand** [comment]
Sima egyenloseg jel az ertekadas, dupla egyenloseg jel pedig feltetel
vizsgalat.
Elso esetben mindig az kapod vissza az if feltetelnek amit az egyenloseg
jel utan irsz, tehat kb mindig igaz.

Tehat if valami=='feltetel'  kell neked

**Comment by tope68** [comment]
A p****ba nem birom megtanulni ezt meg mindig a clipper pascal van....
