### ISSUE TITLE
router location did not match

### ISSUE THREAD

**Issue by tope68** [tope68/ltoregister#8]
No megint itt. :-/ Biztos banalis a hiba. Semmi nem csinaltam, mint felvettem egy uj menupontot (belepes) csinaltam egy "ures" loginpages.js-t csak egy kiiras van benne és felvettem react routerbe. Ha ranyomok ez jon: Warning: [react-router] Location "/loginpage" did not match any routes Nem latok elirast ugy latom mindenhol megvan, ahol kell....

**Comment by tothand** [comment]
Ezt kozben javitottad? Nekem mukodik.
(lehet, hogy kell neki egy komplett meteor restart, mert nem olvasta ujra valamelyik reszet?!)

**Comment by tope68** [comment]
Nem nyultam hozza, de ugy tunk tenyleg a meteor ujrainditas kellett, mert most megy. Ellenben azt menu aktivklassz nem ertem. Miert kell hozza varazsolni (nem is nagon erte mit csinlal, amit irtal), hiszen a link to activeclass pont ezt igeri hogy ezt kezeli le.

**Comment by tope68** [comment]
Amgy mas anomalia is van. Ha jol ertelmezem, akkor amit csinaltal masik varazslas :-) a select option "tomb eloallitojara" ezt írja :  Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Ltochange`

**Comment by tope68** [comment]
Ha jol gondolom erre megfejtes ez https://www.youtube.com/watch?v=XVdwq8W2ZsM 7:40-tol van rola szo

**Comment by tothand** [comment]
Igen, az alapja az.

Valami ilyesmit lehet oda tenni:
`<option key=`ltoa${i}` value={i+1}>{i+1}</option>`

a masiknal meg ltob

Azert nem jo siman a `key={i}`, mert kulonben a 2 tomb azonos indexeket generalna es a key-nek az egesz DOM-on belul egyedinek kell lennie.

Ami a masik kerdest illeti, hogy miert nem mukodik siman az activeClassName, a valasz annyi, hogy a react-router nem 100%-ban kompatibilis a bootstrap-pel, elvileg arra van a react-bootstrap.

**Comment by tothand** [comment]
most nezem, hogy rosszul formazta a github amit irtam

key='ltoa${i}' de backtick (visszafele aposztrof) kell, nem sima
(csak az a karakter itt a commentben specialis jelentessel bir, ezert nem latszodik)

**Comment by tope68** [comment]
Ket kerdes csak hogy ertsem is. Az egyik, hogy nem lenne jo az egyiknek i a masiknak j valtozo? A masik, hogy a backtick minek a szintaktikaja?

**Comment by tothand** [comment]
Nem az a lenyeg, hogy i meg j, hanem hogy mindketto 1...23 kozotti ertekeket vesz fel, tehat mindket select-ben lenne pl. egy 5-os key, ami meghulyitene a react-ot, mert nem egyedi.

Nyilvan ez most itt a legegyszerubb megoldas volt, lehetne sokkal faramucibb is. pl. object-kent letarolni mindket 1..23 sorozatot ahol mellett van egy egyedileg generalt unique key...stb., de ilyen egyszeru feladathoz felesleges.
Ha csak 1 option lenne az oldalon 1 loop (khmm..map) hasznalataval, akkor nem kellene oda semmi backtick meg hasonlo, siman lehetne `key={i}`

A backtick az ES6-ban a template string jele. Tengap emlekszel ezt hasznaltuk arra, hogy az URL-t osszerakjuk valtozokbol.

[https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals)

**Comment by tope68** [comment]
Hmm nem emlékszem hogy hol hasznaltuk.......de unexpetected token hiba van. Ez melyik karaketer az altgr 7 vagy 9?

**Comment by tothand** [comment]
ltolist.js 22. sor
```
browserHistory.push(`/ltochange/${row.ltoAnumber}/${row.ltoBnumber}/${row._id}`);
```

Fogalmam nincs hogy magyar billentyuzeten hol van.
Angolon az 1-es mellett van :)

**Comment by tope68** [comment]
Na latod mar nem is emlekzetm....remenytelen vagyok.... :-( Akkor saccra ez az altgr7 lesz....en meg a 9-est hasznaltm lehet ezert a hiba? :-)

**Comment by tope68** [comment]
Ezzel sem jo....nekem akkor nincs is ilyenem a klavin :-o

**Comment by tothand** [comment]
Fogalmam nincs mi lehetett a hiba, nekem csak 1 ilyen karakterem van :D

Commitold fel es megnezem.
Amugy meg copy-paste az ltolist-bol

Tudom mi lehet a hiba.
igy probald key={'ltoa${i}'}

(persze nem aposztroffal, hanem backtick-el)

Csak fejbol irtam a commentet, nem probaltam ki

**Comment by tope68** [comment]
Igen ezt csinaltam :-) copiztam, betettem a {} jelet majd meteor frissult........11 perc alatt lett meg ez a 3 muvelet...

**Comment by tothand** [comment]
Es most mar jo?

**Comment by tope68** [comment]
Igen, ezt is lezarhatjuk :-)
